---
title: "Example Data Analysis Report"
subtitle: "Built with a parameterized R-markdown report"
author: "Robin Todd"
date: "10/12/2018"
output:
    html_document:
      theme: spacelab
      toc: True
      toc_float: True
      number_sections: True
---
<style type="text/css">
div#TOC li {
    list-style:none;
    background-image:none;
    background-repeat:none;
    background-position:0; 
}
</style>

```{r setup, include=FALSE}
###Add all necessary packages###
library(shiny)
library(survival)
library(tidyverse)
library(survminer)
library(knitr)
library(htmlTable)
library(kableExtra)
library(etable)
library(sas7bdat)
```

```{r data, include=F, echo=F}
###Load data, need list of numerical variables
data  <- read.sas7bdat("/Users/RT/Documents/R coding/Survival Analysis/myel.sas7bdat")
data_main <- data  #data_main is cleaned data

numvars <- c('id', 'dur')
```



#Data Summary

##Frequency table for categorical variables

```{r myel, ref.label="frequencyTable", echo=F}
```

Testing
```{r, echo = F, warning = F}
data_main  <- veteran
numvars = c('time','diagtime','age')
```

```{r veterans, ref.label="frequencyTable", echo=FALSE, warning=F}
```


```{r frequencyTable, echo = F, warning=F, results = 'hide'}
data <- select(data_main, -numvars)
data <- data[,sort(names(data))]

freqTbl<-data %>%
  gather("variable", "value") %>%
  group_by(variable) %>%
  count(variable, value) %>%
  mutate(prop=prop.table(n))

varnames <- (distinct(select(freqTbl, variable)))

a = data.frame(matrix(ncol = 4, nrow=nrow(varnames)))
colnames(a) <- c('groupname','nLevels','begIndex','endIndex')

i=0
a$begIndex[1]=1
while (i< nrow(varnames)){
  i=i+1
  a$groupname[i]=varnames$variable[i]
  a$nLevels[i]=n_distinct(data[,i])
}

i=0
while (i+1 < nrow(a)){
  i=i+1
  a$endIndex[i]=a$begIndex[i]+a$nLevels[i]-1
  a$begIndex[i+1]=a$endIndex[i]+1
  a$endIndex[i+1]=a$begIndex[i+1]+a$nLevels[i+1]-1
}

k <- "kable_styling(kable(freqTbl[,2:4], align = c('l','r','r'),format = 'html'), 'striped', full_width = T)"

teststr <- str_c(k,"%>% group_rows('",as.character(a$groupname[1]),"',",as.character(a$begIndex[1]),",",as.character(a$endIndex[1]),", label_row_css = 'background-color: #666; color: #fff;')")

i=2
while (i < nrow(varnames)+1) {
  teststr=str_c(teststr,"%>% group_rows('",as.character(a$groupname[i]),"',",as.character(a$begIndex[i]),",",as.character(a$endIndex[i]),", label_row_css = 'background-color: #666; color: #fff;')")
i=i+1
}

eval(parse(text=teststr))
```
